### ISSUE TITLE
NAudio 2.0.0

### ISSUE THREAD

**Issue by julianxhokaxhiu** [naudio/Vorbis#11]
Hi,

I was trying to upgrade one my projects to NAudio 2.0, but I'm using also NAudio.Vorbis, which still references NAudio 1.10.

Is there a possibility to upgrade this library to reference NAudio 2.0?

Thank you in advance,
Julian

**Comment by ioctlLR** [comment]
Closed by https://github.com/naudio/Vorbis/tree/v1.3.0 and published to Nuget.
