### ISSUE TITLE
Error handling .oga audio files

### ISSUE THREAD

**Issue by AndresGonzalezDev** [naudio/Vorbis#13]
I'm trying to use this NuGet to convert audio files to .wav format.
With .ogg files works as expected and I get my .wav file successfully, but if I try to convert .oga files  it throws a "Could not initialize container!" exception.

Here's the code I'm using

```
                using (VorbisWaveReader vorbisStream = new VorbisWaveReader("C:/Users/LENOVO/Downloads/test.ogg"))
                {
                    WaveFileWriter.CreateWaveFile("C:/Users/LENOVO/Downloads/test.wav", vorbisStream);
                    Console.WriteLine("Success!");
                }
```
The code above works just fine, but if I try to read the file C:/Users/LENOVO/Downloads/test.oga the process fails when initializing the VorbisWaveReader object.

**Comment by ioctlLR** [comment]
Just based on the error message it looks like there's something "wrong" with your .oga file.  Guessing, it's probably not Vorbis encoded audio.  Can you upload it somewhere and share the link with me so I can take a look?

**Comment by AndresGonzalezDev** [comment]
Here you go: https://s3-external-1.amazonaws.com/media.twiliocdn.com/AC1837b79a66c5a9f6dc778e631ba32f07/cb10fa441fb0277d58be6674058c06b0

I'm not manipulating the audio file at all, I'm just working with Twilio to receive and send messages in Whatsapp, when I send a voice message I get an URL like the one abobe.

**Comment by ioctlLR** [comment]
Got it.  That's an OPUS file, and unfortunately not something this library can decode.

There is probably some value in changing the code to make that more obvious, but I'll have to think about whether to just bubble the exception or do something more intelligent.

In any case, I recommend you either allow NAudio to figure out the codec on its own OR try to use https://github.com/lostromb/concentus instead.
