### ISSUE TITLE
VorbisWaveReader doesn't work as an ISampleProvider

### ISSUE THREAD

**Issue by OronDF343** [naudio/Vorbis#2]
VorbisWaveReader implements ISampleProvider, so it should be usable just like any ISampleProvider. However, when I use it like this:

    var _vorbisReader = new VorbisWaveReader(@"C:\test.ogg");
    var _balanceProvider = new BalanceSampleProvider(_vorbisReader);
    var _waveOut = new DirectSoundOut();
    _waveOut.Init(_balanceProvider);
    _waveOut.Play();

It doesn't play the file and throws a System.ArrayTypeMismatchException
Here is the code of BalanceSampleProvider, where the exception is thrown:

    public class BalanceSampleProvider : ISampleProvider
    {
        private readonly ISampleProvider _source;
        public BalanceSampleProvider(ISampleProvider source)
        {
            if (source.WaveFormat.Channels != 2)
                throw new InvalidOperationException("Input wave format must be stereo!");
            _source = source;
            LeftVolume = 1.0f;
            RightVolume = 1.0f;
        }
        public WaveFormat WaveFormat
        {
            get { return _source.WaveFormat; }
        }

        public int Read(float[] buffer, int offset, int sampleCount)
        {
            int samplesRead;
    
            // Exception is thrown at this line:
            samplesRead = _source.Read(buffer, offset, sampleCount);
    
            if (RightVolume == 1.0f && LeftVolume == 1.0f) return samplesRead;
            for (int n = 0; n < sampleCount; n += 2)
            {
                buffer[offset + n] *= LeftVolume;
                buffer[offset + n + 1] *= RightVolume;
            }
            return samplesRead;
        }

        public float LeftVolume { get; set; }
        public float RightVolume { get; set; }
    }

I'm using NAudio 1.7.3, NVorbis 0.8.4.0, NAudio.Vorbis 1.0.0.0

**Comment by ioctlLR** [comment]
Can you post the stack trace?  We need to know exactly where it is throwing the exception...

**Comment by OronDF343** [comment]
at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at NVorbis.RingBuffer.CopyTo(Single[] buffer, Int32 index, Int32 count)
   at NVorbis.VorbisStreamDecoder.ReadSamples(Single[] buffer, Int32 offset, Int32 count)
   at NVorbis.VorbisReader.ReadSamples(Single[] buffer, Int32 offset, Int32 count)
   at NAudio.Vorbis.VorbisWaveReader.Read(Single[] buffer, Int32 offset, Int32 count)
   at NTest.BalanceSampleProvider.Read(Single[] buffer, Int32 offset, Int32 sampleCount) in d:\#Coding\C#\NTest\NTest\Program.cs:line 44
   at NAudio.Wave.SampleProviders.SampleToWaveProvider.Read(Byte[] buffer, Int32 offset, Int32 count)
   at NAudio.Wave.DirectSoundOut.Feed(Int32 bytesToCopy)
   at NAudio.Wave.DirectSoundOut.PlaybackThreadFunc()

**Comment by markheath** [comment]
this is likely due to a `WaveBuffer` being used somewhere. For the most part this seamlessly allows .NET to write to a `byte[]` as though it were a `float[]`, but the `Array.Copy` and `Array.Clear` functions should be avoided in this case as they use reflection to see what type the array really is. I have a feeling that `Buffer.BlockCopy` will work correctly in this example.

**Comment by ioctlLR** [comment]
Yup.  The WaveBuffer is in SampleToWaveProvider.Read(...).  I'll have to update NVorbis to fix it; stay tuned...

**Comment by ioctlLR** [comment]
@OronDF343, Can you build NVorbis from source and replace the NuGet build you are using?  I think I have it fixed.

**Comment by OronDF343** [comment]
It's fixed now, thanks
