### ISSUE TITLE
VorbisWaveReader gets misaligned

### ISSUE THREAD

**Issue by Alphish** [naudio/Vorbis#3]
I've found that the reader position gets misaligned, especially when seeking is involved.

Apparently, it's caused by VorbisWaveReader using time-based properties (TotalTime, DecodedTime) of underlying Vorbis reader to determine length and position, instead of sample-based ones (TotalSamples, DecodedSamples).

I copy-pasted the VorbisWaveReader code to my project and changed Length and Position definitions to the following:
```c#
public override long Length
{
    get { return _reader.TotalSamples * _waveFormat.BlockAlign; }
}

public override long Position
{
    get
    {
        return _reader.DecodedPosition * _waveFormat.BlockAlign;
    }
    set
    {
        if (value < 0 || value > Length) throw new ArgumentOutOfRangeException("value");

        _reader.DecodedPosition = value / _waveFormat.BlockAlign;
    }
}
```
It did the job for me - I got a fully functional and correctly aligned reader with that.

Could you please update the VorbisWaveReader accordingly? I'd go through with all the forking and PRing procedure, but the change is so small it's probably not worth it.

**Comment by ioctlLR** [comment]
If you'd like to send me a pull request, I'll look it over and merge it.

**Comment by ioctlLR** [comment]
This should now be fixed.
