### ISSUE TITLE
Provide separate volume control functionality like that of NAudio.AudioFileReader

### ISSUE THREAD

**Issue by Rayffer** [naudio/Vorbis#5]
Every channel opened should have its own volume control, could you guys implement this?

**Comment by combatneko** [comment]
This repo hasn't been updated in 4 years. You're probably better off writing your own implementation 😉

**Comment by Rayffer** [comment]
@combatneko have you worked on this repo by any chance?

**Comment by Rayffer** [comment]
Ok, thanks for your time anyways, lovely community :D

**Comment by ioctlLR** [comment]
Per-channel volume functionality is available via NAudio.
