### ISSUE TITLE
InvalidDataException when using NVorbis version 0.8.4

### ISSUE THREAD

**Issue by DoubleCouponDay** [naudio/Vorbis#6]
[If you follow this link](https://github.com/ioctlLR/NVorbis/issues/22), you will find an investigation into this error upon attempting to read an ogg file.

I recommend the maintainer of this library to update the NVorbis version to at least 0.8.6 as this will fix this edge case from occurring.

**Comment by ioctlLR** [comment]
@markheath do you have time to do a new release?  I'm not sure how soon I can do it.

@DoubleCouponDay I think you can manually tell Nuget to use NVorbis 0.8.6 so you don't have to wait for us.

**Comment by ioctlLR** [comment]
Fix released as v1.1.0.  Update your nuget packages.  NOTE: If you're still on .Net Framework < v4.5, you'll need to update.
