### ISSUE TITLE
Could not load stream 0 due to error: Found OPUS bitstream.

### ISSUE THREAD

**Issue by TonyHenrique** [naudio/Vorbis#9]
I have some .ogg file received from WhatsApp, and tried to load it using NAudio.Vorbis.VorbisWaveReader(@"C:\Users\tonyv\Downloads\a.ogg");
But it throws this Exception: **`Could not load stream 0 due to error: Found OPUS bitstream.`**

```
iisexpress.exe Warning: 0 : Could not load stream 0 due to error: Found OPUS bitstream.
Exception thrown: 'System.ArgumentException' in NAudio.Vorbis.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
An exception of type 'System.ArgumentException' occurred in mscorlib.dll but was not handled in user code
Could not initialize container!
```

How can I load it using NAudio?

_Did a quick search and found that Opus is the successor for Vorbis, created by the same company and applicable to a wider range of audio qualities and rates while having low latency. When Opus is available, there is no real reason to prefer Vorbis over it except possibly for catering for older playback devices. https://sound.stackexchange.com/a/42712/32515_

**Comment by ioctlLR** [comment]
https://github.com/naudio/NAudio/issues/674 covers this (sorta).  Probably the easiest answer is to use the MediaFoundationReader type to load the file (assuming a new enough Windows 10 install).

**Comment by TonyHenrique** [comment]
In a first aspproach, I used FFMpegCore (ffmpeg.exe) to convert that .ogg file to .wav required format.

Then I changed my code to use AWS and just send the original .ogg file.

It will be cool to have this ogg/Opus support on NAudio.

**Comment by ioctlLR** [comment]
I'd like to see this, too, but it will have to be a separate project.  As such, we're closing this issue.
